config/routes.rb
Medglobal::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :clinic_requests
  get "home/index"
  resources :shops do 
    resources :locations
    resources :services
    resources :staffs
    resources :promotions
    resources :reviews
    resources :appointments
    resources :messages
    resources :photos
  end

  get "/about", to: 'pages#show', id: 'about_us'
  get "/terms", to: 'pages#show', id: 'terms'
  get "/privacy", to: 'pages#show', id: 'privacy'

  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appointment.rb
class Appointment < Message

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :services
  has_and_belongs_to_many :shops
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  belongs_to :shop
end

app/models/clinic_request.rb
class ClinicRequest < Message
  REQUEST_DATA = [:staff_info, :location, 
                  :name, :email, 
                  :shop_info, :legal,
                  :clinic_name]

  attr_accessor *REQUEST_DATA

  QUESTIONS = 
    { 
      staff_info: "How many doctors do you have?",
      location: "What is your address?",
      name: "Contact Person's Name",
      phone: "Contact Phone Number",
      email: "Email Address",
      shop_info: "What kind of services do you provide?",
      legal: "Have you or your staff encountered any legal problems/issues?",
      clinic_name: "What is the name of your clinic/hospital?"
    }

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :shop

  # validates :name, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :url, presence: true

  def self.by_city(city_name)
    where("city = ?", city_name)
  end

  reverse_geocoded_by :lat, :lng do |obj,results|
    if geo = results.first
      obj.city    = geo.city
      obj.zipcode = geo.postal_code
      obj.country = geo.country
    end
  end
  after_validation :reverse_geocode, if: -> { lat.present? and lng.present? }
  
  def self.distinct_cities
    pluck(:city).compact.uniq
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
  belongs_to :shop

  attr_accessor :phone

  after_create :collect_name_and_phone, if: -> { phone and user }

  def collect_name_and_phone
    user.phone = phone
    user.save
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :shop

  mount_uploader :name, ImageUploader

  def self.main_only
    where(main: true).first
  end
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :location
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop

  validates :score, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :shop


  def self.distinct_by_name
    pluck(:name).uniq
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :reviews,      dependent: :destroy
  has_many :promotions,   dependent: :destroy
  has_many :certificates, dependent: :destroy
  has_many :staffs,        dependent: :destroy
  has_many :photos,       dependent: :destroy
  has_many :services,     dependent: :destroy
  has_many :locations,    dependent: :destroy
  has_many :users, through: :reviews

  has_many :messages
  has_many :appointments

  validates :name, presence: true
  
  accepts_nested_attributes_for :locations, reject_if: :all_blank
  accepts_nested_attributes_for :services, reject_if: :all_blank
  accepts_nested_attributes_for :staffs, reject_if: :all_blank

  has_and_belongs_to_many :categories
  belongs_to :user

  # allowing the shop to be searched by city name
  def self.by_city(city_name) 
    city_name.present? ? joins(:locations).where(locations: { city: city_name }) : all
  end

  # allowing the shop to be searched by country name
  def self.by_country(country_name)
    country_name.present? ? joins(:locations).where(locations: { country: country_name }) : all
  end

  def self.by_service(service_name)
    service_name.present? ? joins(:services).where(services: { name: service_name }) : all
  end

  def self.by_category(category_id)
    category_id.present? ? joins(:categories).where(categories: { id: category_id }) : all
  end

  def average_score
    if reviews.count > 0
      reviews.sum(:score) / reviews.count
    else 0 end
  end
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :shop

  mount_uploader :avatar, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :shops
  has_many :messages
  has_many :appointments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    read_attribute(:name) || read_attribute(:email)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_filter :authenticate_admin_user!, except: [:index, :show]

  layout 'shop_profile_form', only: [:edit]
  # needs specific user during create, edit except during index or show
  # current_user.shops. build or where is to specify that user is needed

  def index
    @shops = Shop.by_city(params[:city])
                 .by_service(params[:service])
                 .by_category(params[:category_id])
  end

  def show
    @shop = Shop.where(id: params[:id]).first
  end

  def new
    @shop = Shop.new
    1.times { @shop.locations.build }
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to edit_shop_path(@shop)
    else
      render :new
    end
  end

  def edit
    @shop = Shop.where(id: params[:id]).first
  end

  def update
    @shop = Shop.where(id: params[:id]).first
    if @shop.update_attributes(shop_params)
      redirect_to edit_shop_path(@shop)
    else
      render :edit
    end

  end

  def destroy
    @shop = Shop.where(id: params[:id]).first
    @shop.destroy
    redirect_to shops_path
  end

private
  def shop_params
    params.require(:shop).permit(:name, :description, :highlights, 
                                 :hours_operation, :payment_methods, :insurance_terms, 
                                 :certifications, :additional_services, :years_business, 
                                 category_ids: [], locations_attributes: [:id, :address])
  end
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper

  def render_lead_collector
    if user_signed_in?
      render 'lead'
    else
      render 'auth_request'
    end
  end
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/views/shops/_appointment.html.erb
<%= form_for [@shop, @shop.appointments.build] do |f|%>
  <div class='form-group'>
    <div><%= f.label :scheduled_at, "Date & Time" %></div>
    <div><%= f.date_field :scheduled_at, class: 'form-control' %></div>
    <div><%= f.label :service_id, "Procedure" %></div>
    <div><%= f.select :service_id, @shop.services.map { |s| [s.name, s.id]} ,class: 'form-control' %></div>
    <div><%= f.label :body, "Message" %></div>
    <div><%= f.text_area :body, class: 'form-control' %></div>

    <div><%= f.label :phone, "Phone" %></div>
    <div><%= f.text_field :phone, class: 'form-control' %></div>
    <div><%= f.submit "Send" , class: 'btn-success btn' %></div>
  </div>
<% end %>

app/views/shops/_auth_request.html.erb
<div class='row'>
  <div>
    <p><h3>Registration</h3>Register to schedule an appointment or contact the clinic</p>
      <div class='form-group'>
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>

        <div><%= f.label :name %></div>
        <div><%= f.text_field :name, class: 'form-control' %></div>

        <div><%= f.label :email %></div>
        <div><%= f.email_field :email, :autofocus => true, class: 'form-control' %></div>

        <div><%= f.label :password %></div>
        <div><%= f.password_field :password, class: 'form-control' %></div>

        <div><%= f.label :password_confirmation %></div>
        <div><%= f.password_field :password_confirmation, class: 'form-control' %></div>

        <div><%= f.submit "Sign up" %></div>
        <% end %>
      </div>
  </div>

  <div>
    <p><h3>Sign In</h3>Sign in to schedule an appointment or contact the clinic</p>
      <div class='form-group'>
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
          <div><%= f.label :email %></div>
          <div><%= f.email_field :email, :autofocus => true, class: 'form-control' %></div>

          <div><%= f.label :password %></div>
          <div><%= f.password_field :password, class: 'form-control' %></div>

          <% if devise_mapping.rememberable? -%>
            <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
          <% end -%>

          <div><%= f.submit "Sign in" %></div>
        <% end %>
      </div>
  </div>



<!-- <div class='row'>
  <div class='col-md-6'>
    <h4>Register</h4>
    <div class='form-group'>
      <#%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
      <#%= devise_error_messages! %>

      <div><#%= f.label :name %></div>
      <div><#%= f.text_field :name, class: 'form-control' %></div>

      <div><#%= f.label :email %></div>
      <div><#%= f.email_field :email, :autofocus => true, class: 'form-control' %></div>

      <div><#%= f.label :password %></div>
      <div><#%= f.password_field :password, class: 'form-control' %></div>

      <div><#%= f.label :password_confirmation %></div>
      <div><#%= f.password_field :password_confirmation, class: 'form-control' %></div>

      <div><#%= f.submit "Sign up" %></div>
      <#% end %>
    </div>
  </div>

  <div class='col-md-6'>
  <h4>Sign in</h4>
    <div class='form-group'>
      <#%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
        <div><#%= f.label :email %></div>
        <div><#%= f.email_field :email, :autofocus => true, class: 'form-control' %></div>

        <div><#%= f.label :password %></div>
        <div><#%= f.password_field :password, class: 'form-control' %></div>

        <#% if devise_mapping.rememberable? -%>
          <div><#%= f.check_box :remember_me %> <#%= f.label :remember_me %></div>
        <#% end -%>

        <div><#%= f.submit "Sign in" %></div>
      <#% end %>
    </div>

  </div>
</div> -->

app/views/shops/_basic.html.erb
<h3>Basic Info</h3>
<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<!-- <h3>Locations</h3>
<div class='form-group'>
  <#%= f.fields_for :locations do |l| %>
    <div><%#= l.label :lat %></div>
    <div><%#= l.number_field :lat, class: 'form-control' %></div>
    <div><%#= l.label :lng %></div>
    <div><%#= l.number_field :lng, class: 'form-control' %></div>
    <div><%#= l.label :address %></div>
    <div><%#= l.text_area :address, class: 'form-control' %></div>
  <#% end %>
</div> -->

<h3>Categories/Specialties</h3>
<div class='form-group'>
    <% for category in Category.all %>
      <div>
        <%= check_box_tag "shop[category_ids][]", category.id, @shop.categories.include?(category) %>
        <%= category.name %>
      </div>
    <% end %>
</div>
  

    

app/views/shops/_contact.html.erb
<%= form_for [@shop, @shop.messages.build] do |f|%>
  <div class='form-group'>

    <div><%= f.label :phone, "Phone" %></div>
    <div><%= f.text_field :phone, class: 'form-control' %></div>
    <div><%= f.label :body, "Message" %></div>
    <div><%= f.text_area :body, class: 'form-control' %></div>
    <div><%= f.submit "Send" , class: 'btn-success btn' %></div>
  </div>
<% end %>

app/views/shops/_form.html.erb
<%= form_for @shop do |f| %>
  <%= render 'basic', f: f %>
  <div>
    <h3>Clinic Details</h3>
    <div class='form-group'>
    <%= f.label :description, "About Us" %>
      <div>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div>
    <%= f.label :highlights, "Highlights" %>
      <div>
        <%= f.text_area :highlights, class: 'form-control' %>
      </div>
  </div>
  <div>
    <%= f.label :hours_operation, "Hours of Operation" %>
      <div>
        <%= f.text_area :hours_operation, class: 'form-control' %>
      </div>
  </div>
  <div>
    <%= f.label :payment_methods, "Accepted Payment Methods" %>
      <div>
        <%= f.text_area :payment_methods, class: 'form-control' %>
      </div>
  </div>
  <div>
    <%= f.label :insurance_terms, "Accepted Insurance Terms" %>
      <div>
        <%= f.text_area :insurance_terms, class: 'form-control' %>
      </div>
  </div>
  <div>
    <%= f.label :certifications, "Certifications" %>
      <div>
        <%= f.text_area :certifications, class: 'form-control' %>
      </div>
  </div>
  <div>
    <%= f.label :additional_services, "Additional Services" %>
      <div>
        <%= f.text_area :additional_services, class: 'form-control' %>
      </div>
  </div>
  <div>
    <%= f.label :years_business, "Years in Business" %>
      <div>
        <%= f.text_area :years_business, class: 'form-control' %>
      </div>
  </div>

  
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/_lead.html.erb
<div>
  <h4>Schedule an appointment</h4>
  <%= render 'appointment' %>
</div>

<div>
  <h4>Contact the clinic</h4>
  <%= render 'contact' %>
</div>

<!-- <div class='row'>
  <div class='col-md-6'>
    <h4>Appointment form</h4>
    <#%= render 'appointment' %>
  </div>

  <div class='col-md-6'>
    <h4>Contact form</h4>
    <#%= render 'contact' %>
  </div>
</div> -->

app/views/shops/_shop.html.erb
<%= div_for shop do %>
  <div class='row'>
    <div class='col-md-3'>
      <!-- <#%= image_tag shop.photos.main_only.name.url, :width => 200 %> -->
    </div>
    <div class='col-md-7'>
      <div>
        <h4><%= link_to shop.name, shop_path(shop) %></h4>
      </div>
      <div>
        <b>Reviews:</b> <span class='review' data-score='<%= shop.average_score %>'></span><span>(<%= shop.reviews.count %>)</span>
      </div>
      <div>
        <% shop.locations.pluck(:city, :address, :tel, :url).uniq.each do |location| %>
        <div>
          <p><b>City</b> <%= location[0] %></p>
        </div>
        <div>
          <p><b>Address</b> <%= location[1] %></p>
        </div>
        <div>
          <p><b>Tel</b> <%= location[2] %></p>
        </div>
        <div>
          <p><b>Website</b> <%= location[3] %></p>
        </div>
        <% end %>
      </div>
    </div>
    <div class='col-md-2'>
      <%= link_to "Select Clinic", shop_path(shop), class: "btn btn-primary btn-block" %>
    </div>
<% end %>
</div>    

app/views/shops/edit.html.erb
<h2>Edit: <%= @shop.name %></h2>
<%= render 'form' %>

app/views/shops/index.html.erb
<div class='row'>
  <div class='col-md-9'> <!-- start left column -->
    <% @shops.each do |shop| %>
      <%= render shop %>
    <% end %>      
      
  </div> <!-- end left column -->

  <div class='col-md-3'> <!-- start right column -->
    <h3>Refine your search</h3>
        <%= render 'application/sidesearch' %>
        <!-- <popular sectors or cuisines> -->
        <div>
          <h3>Popular Treatments</h3>
            <p>Malaysia</p>
            <p>Malaysia</p>
            <p>Malaysia</p>
        </div>
        <!-- <Top cities> -->
        <div>
          <h3>Top cities</h3>
            <p>Bangkok</p>
            <p>Phuket</p>
            <p>Pattaya</p>
        </div>
      </div>
  </div> <!-- end right column -->
<div>

app/views/shops/new.html.erb
<h2>Create your new clinic - Basic Information</h2>
<%= form_for @shop, html: { class: 'col-md-6 col-md-offset-3' } do |f| %>
  <%= render 'basic', f: f %>
  <div class='form-group'>
    <%= f.submit "Next", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/shops/original_show.html.erb
<div class='row'>
  <div class='col-md-9'> <!-- start left column -->
    <div class='row'>
      <div class='col-md-9'>
        <h2><%= @shop.name %></h2>
        <%= image_tag 'ratings_holder.jpg', alt: 'ratings!', class: 'img-thumbnail' %> 213 reviews
      </div>
      <div class='col-md-3'>
        <button type="button" class="btn btn-success btn-lg btn-block">Appointment</button>
        <button type="button" class="btn btn-warning btn-lg btn-block">Contact</button>
      </div>
    </div>
      <div>
        <%= image_tag 'clinic_holder.jpg', alt: 'clinic!', class: 'img-thumbnail' %>
      </div>
      <div>
        <%= image_tag 'map_holder.jpg', alt: 'map!', class: 'img-thumbnail' %>
        <% @shop.locations.each do |location| %>
          <span><%= location.address %></span>
        <% end %>
      </div>
      <div>
        <%= image_tag 'cert_holder.jpg', alt: 'certificate!', class: 'img-thumbnail' %>Cert name 
        <%= image_tag 'cert_holder.jpg', alt: 'certificate!', class: 'img-thumbnail' %>Verified
      </div>
      <div class='row'>
        <div class='col-md-6'>
          <h4>Highlights</h4>
          <p><%= simple_format @shop.highlights %></p>
        </div>
        <div class='col-md-6'>
          <h4>Hours of Operation</h4>
          <p><%= simple_format @shop.hours_operation %></p>
        </div>
      </div>
      <h4>About the Clinic</h4>
      <p><%= simple_format @shop.description %></p>

      <h4>Payment Methods</h4>
      <p><%= simple_format @shop.payment_methods %></p>

      <h4>Insurance Terms</h4>
      <p><%= simple_format @shop.insurance_terms %></p>

      <h4>Certifications</h4>
      <p><%= simple_format @shop.certifications %></p>

      <h4>Additional Services</h4>
      <p><%= simple_format @shop.additional_services %></p>

      <h4>Years In Business</h4>
      <p><%= simple_format @shop.years_business %></p>
  </div>

  <div class='col-md-3'> <!-- start right column -->
    <h2>Find a Clinic</h2>
        <div>
          <h3>Treatment</h3>
            <input type="text" class="form-control" placeholder="Crown, Implants, Dentures">
          <h3>Location</h3>
            <input type="text" class="form-control" placeholder="Mexico, Costa Rica, Bangkok">
        </div>
        <div id='advanced'>
          <a href='#'>Advanced Search</a>
            <div id='advanced-fields'>
              <h3>Clinic</h3>
                <input type="text" class="form-control" placeholder="Search by name">
              <h3>Doctor</h3>
                <input type="text" class="form-control" placeholder="Find a Doctor">
            </div>
        </div>
        <div>
          <button type="button" class="btn btn-success">Search Now</button>
        </div>
        <!-- <popular sectors or cuisines> -->
        <div>
          <h2>Popular Treatments</h2>
            <p>Malaysia</p>
            <p>Malaysia</p>
            <p>Malaysia</p>
        </div>
        <!-- <Top cities> -->
        <div>
          <h2>Top cities</h2>
            <p>Bangkok</p>
            <p>Phuket</p>
            <p>Pattaya</p>
        </div>
  </div>

<span>
  <%= link_to "Edit: #{@shop.name}", edit_shop_path(@shop) %>
</span>

<span>
  <%= link_to "Delete", shop_path(@shop), method: :delete, data: { confirm: "Are you sure?"} %>
</span>

<span>
  <%= link_to "Back to All Shops", shops_path %>
</span>

app/views/shops/show.html.erb
<div class='row'>
  <%= div_for @shop, class: 'col-md-9' do %><!-- start left column -->
    <h2><%= @shop.name %></h2>
    <p>
      Reviews: <span class='review' data-score='<%= @shop.average_score %>'></span><span>(<%= @shop.reviews.count %>)</span>
    </p>
    <p>
      <b>Address:</b>  <%=@shop.locations.first.address %>
    </p>
    <p>
      <b>Tel:</b>  <%=@shop.locations.first.tel %>
      <b>Website:</b> <%=@shop.locations.first.url %>
    </p>

    <div class='row'> <!-- start first row --> 
      <div>
        <%= image_tag @shop.photos.main_only.name.url, :width => 650 %>
      </div>
    </div><!-- end first row -->

  <div class='row'>
    <div>
      <h4>Reviews</h4>
      <%= render @shop.reviews %>
      <p><h4>Write a review</h4>Sign in or Register to review</p>
      <%= render 'reviews/new' %>
    </div>
  </div>


  <div class='row'>
    <!-- Nav tabs -->
      <ul class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">Contact</a></li>
        <li><a href="#profile" data-toggle="tab">Profile</a></li>
        <li><a href="#services" data-toggle="tab">Services</a></li>
        <li><a href="#gallery" data-toggle="tab">Gallery</a></li>
        <li><a href="#specialists" data-toggle="tab">Specialists</a></li>
        <li><a href="#promotions" data-toggle="tab">Promotions</a></li>
      </ul>

    <!-- Tab panes -->

      <div class="tab-content">
        <div class="tab-pane active" id="home">
            <div class='row'>
              <div class='col-md-8'>
                <h4>Map</h4>
                <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@shop.locations.first.lat}, #{@shop.locations.first.lng}&zoom=14&size=700x400", alt: 'map!', class: 'img-thumbnail' %>
              </div>
              <div class='col-md-4'>
                <p>
                  <h4>Address</h4>  <%=@shop.locations.first.address %>
                </p>
                <p>
                  <h4>Tel</h4>  <%=@shop.locations.first.tel %>
                </p>
                <p>
                  <h4>Website</h4>  <%=@shop.locations.first.url %>
                </p>
              </div>
          </div>
        </div>

      <div class="tab-pane" id="profile">
          <div class='row'>
            <div class='col-md-8'>
              <h4>Highlights</h4>
                <p><%= simple_format @shop.highlights %></p>

              <h4>About the Clinic</h4>
                <p><%= simple_format @shop.description %></p>

              <h4>Additional Services</h4>
                <p><%= simple_format @shop.additional_services %></p>
              <!-- <div>
                <h4>Location</h4>
                
                <#%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@shop.locations.first.lat}, #{@shop.locations.first.lng}&zoom=14&size=600x300", alt: 'map!', class: 'img-thumbnail' %>
              </div> -->
            </div> 

            <div class='col-md-4'>
                <h4>Hours of Operation</h4>
                  <p><%= simple_format @shop.hours_operation %></p>

                <h4>Payment Methods</h4>
                  <p><%= simple_format @shop.payment_methods %></p>

                <h4>Insurance Terms</h4>
                  <p><%= simple_format @shop.insurance_terms %></p>

                <h4>Certifications</h4>
                  <p><%= simple_format @shop.certifications %></p>

                <h4>Years In Business</h4>
                  <p><%= simple_format @shop.years_business %></p>
              </div>
            </div>
        </div>

        

        <div class="tab-pane" id="services">
          <div>
            <h4>Services</h4>
              <div class='table-responsive'>
                <table class='table'>
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Duration</th>
                  </tr>
                <% @shop.services.each do |service| %>
                  <tr>
                    <td><%= service.name %></td>
                    <td><%= service.description %></td>
                    <td><%= service.price %></td>
                    <td><%= service.duration %></td>
                  </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>

        <div class="tab-pane" id="gallery">
          <div>
            <h4>Gallery</h4>
              <div class='table-responsive'>
                <table class='table'>
                  <tr>
                    <% @shop.photos.each_with_index do |photo,index| %>
                    <% if index > 0 && index % 3 == 0 then %>
                    </tr><tr>
                    <% end %>
                    <td><%= image_tag photo.name, :width => 200 %></td>
                    <% end %>
                  </tr>
                </table>
            </div>
           </div>
        </div>

        <div class="tab-pane" id="specialists">
          <div>
            <h4>Specialists</h4>
            <div class='table-responsive'>
              <table class='table'>
                <% @shop.staffs.each do |staff| %>
                <tr>
                  <th><%= staff.name %></th>
                  <th>Education</th>
                  <th>Skills</th>
                </tr>
                <tr>
                  <td><%= image_tag staff.avatar.url, :width => 100 %></td>
                  <td><%= staff.education %></td>
                  <td><%= staff.skills %></td>
                </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>

        <div class="tab-pane" id="promotions">
          <div>
            <h4>Promotions</h4>
            <div class='table-responsive'>
              <table class='table'>
                <% @shop.promotions.each do |promotion| %>
                <tr>
                  <th><%= promotion.title %></th>
                  <th>Description</th>
                  <th>Expiry Date</th>
                </tr>
                <tr>
                  <td><%#= image_tag promotion.avatar.url, :width => 150 %></td>
                  <td><%= promotion.description %></td>
                  <td><%= promotion.exp_date %></td>
                </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
    </div>
  </div>
  
    

<% end %><!-- end left column -->


    <div class='col-md-3'> <!-- start right column -->
      <div id='lead_collection'>
        <%= render_lead_collector %>
      </div>

      <div>
        <h3>Search again</h3>
          <%= render 'application/sidesearch' %>
      </div>
      
    </div> <!-- end right column -->
  </div>
</div>


<!-- <span>
  <#%= link_to "Edit: #{@shop.name}", edit_shop_path(@shop) %>
</span>

<span>
  <#%= link_to "Delete", shop_path(@shop), method: :delete, data: { confirm: "Are you sure?"} %>
</span>

<span>
  <#,%= link_to "Back to All Shops", shops_path %>
</span> -->