config/routes.rb
Medglobal::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :clinic_requests
  get "home/index"
  resources :shops do 
    resources :locations
    resources :services
    resources :staffs
    resources :promotions
    resources :reviews
    resources :appointments
    resources :messages
    resources :photos
  end

  get "/about", to: 'pages#show', id: 'about_us'
  get "/terms", to: 'pages#show', id: 'terms'
  get "/privacy", to: 'pages#show', id: 'privacy'

  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appointment.rb
class Appointment < Message

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :services
  has_and_belongs_to_many :shops
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  belongs_to :shop
end

app/models/clinic_request.rb
class ClinicRequest < Message
  REQUEST_DATA = [:staff_info, :location, 
                  :name, :email, 
                  :shop_info, :legal,
                  :clinic_name]

  attr_accessor *REQUEST_DATA

  QUESTIONS = 
    { 
      staff_info: "How many doctors do you have?",
      location: "What is your address?",
      name: "Contact Person's Name",
      phone: "Contact Phone Number",
      email: "Email Address",
      shop_info: "What kind of services do you provide?",
      legal: "Have you or your staff encountered any legal problems/issues?",
      clinic_name: "What is the name of your clinic/hospital?"
    }

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :shop

  # validates :name, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :url, presence: true

  def self.by_city(city_name)
    where("city = ?", city_name)
  end

  reverse_geocoded_by :lat, :lng do |obj,results|
    if geo = results.first
      obj.city    = geo.city
      obj.zipcode = geo.postal_code
      obj.country = geo.country
    end
  end
  after_validation :reverse_geocode, if: -> { lat.present? and lng.present? }
  
  def self.distinct_cities
    pluck(:city).compact.uniq
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
  belongs_to :shop

  attr_accessor :phone

  after_create :collect_name_and_phone, if: -> { phone and user }

  def collect_name_and_phone
    user.phone = phone
    user.save
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :shop

  mount_uploader :name, ImageUploader

  def self.main_only
    where(main: true).first
  end
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :location
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop

  validates :score, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :shop


  def self.distinct_by_name
    pluck(:name).uniq
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :reviews,      dependent: :destroy
  has_many :promotions,   dependent: :destroy
  has_many :certificates, dependent: :destroy
  has_many :staffs,        dependent: :destroy
  has_many :photos,       dependent: :destroy
  has_many :services,     dependent: :destroy
  has_many :locations,    dependent: :destroy
  has_many :users, through: :reviews

  has_many :messages
  has_many :appointments

  validates :name, presence: true
  
  accepts_nested_attributes_for :locations, reject_if: :all_blank
  accepts_nested_attributes_for :services, reject_if: :all_blank
  accepts_nested_attributes_for :staffs, reject_if: :all_blank

  has_and_belongs_to_many :categories
  belongs_to :user

  # allowing the shop to be searched by city name
  def self.by_city(city_name) 
    city_name.present? ? joins(:locations).where(locations: { city: city_name }) : all
  end

  # allowing the shop to be searched by country name
  def self.by_country(country_name)
    country_name.present? ? joins(:locations).where(locations: { country: country_name }) : all
  end

  def self.by_service(service_name)
    service_name.present? ? joins(:services).where(services: { name: service_name }) : all
  end

  def self.by_category(category_id)
    category_id.present? ? joins(:categories).where(categories: { id: category_id }) : all
  end

  def average_score
    if reviews.count > 0
      reviews.sum(:score) / reviews.count
    else 0 end
  end
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :shop

  mount_uploader :avatar, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :shops
  has_many :messages
  has_many :appointments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    read_attribute(:name) || read_attribute(:email)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper

  def render_lead_collector
    if user_signed_in?
      render 'lead'
    else
      render 'auth_request'
    end
  end
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/views/home/index.html.erb
<div class='jumbotron' style='background: transparent url(<%= asset_url('home_background.jpg') %>) no-repeat'>
  <div class='container'>
    <div class='row' id='search_bar'>

      <div class'col-md-6'>
        <h3>Find the right clinic or hospital abroad - Dental, Cosmetic, General Checkups</h3>
        <h4>Quality care | Low cost | No delays</h4>
        <%= render 'application/search' %>
      </div>

    </div>
  </div>
</div>

<div class='container'>

  <div class='row'>
    <div class='col-md-3'>
        <h4>Submit your clinic</h4>
        <p>Are you a top dentist or specialist? Get listed now!</p>
        <%= link_to new_clinic_request_path do %>
          <button type="button" class="btn btn-success">Submit now</button>
        <% end %>
    </div>

    <div class='col-md-3'>
      <h4>Popular Specialties</h4>
      <ul>
        <% Category.all.each do |category| %>
          <li><%= link_to category.name, shops_path + "?category_id=#{category.id}" %></li>
        <% end %>
      </ul>
    </div>

    <div class='col-md-3'>
      <h4>Popular Procedures</h4>
      <ul>
        <% Service.distinct_by_name.each do |service| %>
          <li><%= link_to service, shops_path + "?service=#{service}" %></li>
        <% end %>
      </ul>
    </div>

    <div class='col-md-3'>
      <h4>Popular Locations</h4>
      <ul>
        <% Location.distinct_cities.each do |location| %>
          <li><%= link_to location, shops_path + "?city=#{location}"  %></li>
        <% end %>
      </ul>    
    </div>

  </div>

</div>