config/routes.rb
Medglobal::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :clinic_requests
  get "home/index"
  resources :shops do 
    resources :locations
    resources :services
    resources :staffs
    resources :promotions
    resources :reviews
    resources :appointments
    resources :messages
    resources :photos
  end

  get "/about", to: 'pages#show', id: 'about_us'
  get "/terms", to: 'pages#show', id: 'terms'
  get "/privacy", to: 'pages#show', id: 'privacy'

  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appointment.rb
class Appointment < Message

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :services
  has_and_belongs_to_many :shops
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  belongs_to :shop
end

app/models/clinic_request.rb
class ClinicRequest < Message
  REQUEST_DATA = [:staff_info, :location, 
                  :name, :email, 
                  :shop_info, :legal,
                  :clinic_name]

  attr_accessor *REQUEST_DATA

  QUESTIONS = 
    { 
      staff_info: "How many doctors do you have?",
      location: "What is your address?",
      name: "Contact Person's Name",
      phone: "Contact Phone Number",
      email: "Email Address",
      shop_info: "What kind of services do you provide?",
      legal: "Have you or your staff encountered any legal problems/issues?",
      clinic_name: "What is the name of your clinic/hospital?"
    }

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :shop

  # validates :name, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :url, presence: true

  def self.by_city(city_name)
    where("city = ?", city_name)
  end

  reverse_geocoded_by :lat, :lng do |obj,results|
    if geo = results.first
      obj.city    = geo.city
      obj.zipcode = geo.postal_code
      obj.country = geo.country
    end
  end
  after_validation :reverse_geocode, if: -> { lat.present? and lng.present? }
  
  def self.distinct_cities
    pluck(:city).compact.uniq
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
  belongs_to :shop

  attr_accessor :phone

  after_create :collect_name_and_phone, if: -> { phone and user }

  def collect_name_and_phone
    user.phone = phone
    user.save
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :shop

  mount_uploader :name, ImageUploader

  def self.main_only
    where(main: true).first
  end
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :location
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop

  validates :score, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :shop


  def self.distinct_by_name
    pluck(:name).uniq
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :reviews,      dependent: :destroy
  has_many :promotions,   dependent: :destroy
  has_many :certificates, dependent: :destroy
  has_many :staffs,        dependent: :destroy
  has_many :photos,       dependent: :destroy
  has_many :services,     dependent: :destroy
  has_many :locations,    dependent: :destroy
  has_many :users, through: :reviews

  has_many :messages
  has_many :appointments

  validates :name, presence: true
  
  accepts_nested_attributes_for :locations, reject_if: :all_blank
  accepts_nested_attributes_for :services, reject_if: :all_blank
  accepts_nested_attributes_for :staffs, reject_if: :all_blank

  has_and_belongs_to_many :categories
  belongs_to :user

  # allowing the shop to be searched by city name
  def self.by_city(city_name) 
    city_name.present? ? joins(:locations).where(locations: { city: city_name }) : all
  end

  # allowing the shop to be searched by country name
  def self.by_country(country_name)
    country_name.present? ? joins(:locations).where(locations: { country: country_name }) : all
  end

  def self.by_service(service_name)
    service_name.present? ? joins(:services).where(services: { name: service_name }) : all
  end

  def self.by_category(category_id)
    category_id.present? ? joins(:categories).where(categories: { id: category_id }) : all
  end

  def average_score
    if reviews.count > 0
      reviews.sum(:score) / reviews.count
    else 0 end
  end
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :shop

  mount_uploader :avatar, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :shops
  has_many :messages
  has_many :appointments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    read_attribute(:name) || read_attribute(:email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def activeable_link_to(text, path, options = {})
    active = if request.path == path then 'active' end
      content_tag :li, class: active  do
        link_to text, path, options
      end
    end

    def user_nav
      if user_signed_in?
        'signed_in'
      else
        'signed_out'
      end
    end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper

  def render_lead_collector
    if user_signed_in?
      render 'lead'
    else
      render 'auth_request'
    end
  end
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/views/application/_flash.html.erb
<% if flash.keys.present? %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/application/_footer.html.erb
<p>
  © 2014 ClinicsAbroad.com, Inc. | 
  <%= link_to "About", about_path %> | 
  <%= link_to "Contact", about_path %> | 
  <%= link_to "Terms", terms_path %> |
  <%= link_to "Privacy", privacy_path %> |
  <a href="https://plus.google.com/111411763848786474737" rel="publisher">Google+</a> | 
  <a href="https://www.facebook.com/pages/Clinics-Abroad/1399545676980155">Facebook</a> | 
  <a href="https://twitter.com/clinicsabroad">Twitter</a> |
  <%= image_tag 'verisign.png', alt: 'verisign!', class: 'img-thumbnail', width: '100px' %>
</p>

app/views/application/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class='container'>
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag 'ca_logo.png', alt: 'clinic!', class: 'img-thumbnail', width: '235px' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <#%= activeable_link_to "Home", root_path %>
        <#%= activeable_link_to "All Clinics", shops_path %> -->
        <%= activeable_link_to "New Clinic", new_shop_path if admin_user_signed_in? %>
      </ul>
      <ul id='right-navbar' class='nav navbar-nav navbar-right'>
        <%= render user_nav %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</div>

app/views/application/_search.html.erb
<%= form_tag shops_path, method: :get, class: 'row' do %>
  <div class='col-md-3'>
    <h4>Specialty</h4>
    <%= select_tag :category_id, options_for_select(Category.all.collect { |c| [c.name, c.id]}), prompt: "", class: 'form-control chosen-select' %>
  </div>
  <div class='col-md-3'>
    <h4>Procedure</h4>
    <%= select_tag :service, options_for_select(Service.distinct_by_name), prompt: "", class: 'form-control chosen-select' %>
  </div>
  <div class='col-md-3'>
    <h4>City</h4>
    <%= select_tag :city, options_for_select(Location.distinct_cities), prompt: "", class: 'form-control chosen-select' %>
  </div>
  <div class='col-md-3'>
    <%= submit_tag "Search Now", class: 'btn btn-success btn-block', id: 'search_button' %>
  </div>
<% end %>

app/views/application/_sidesearch.html.erb
<%= form_tag shops_path, method: :get do %>
<div>
  <h5>Category</h5>
  <%= select_tag :category_id, options_for_select(Category.all.collect { |c| [c.name, c.id]}), prompt: "", class: 'form-control' %>
</div>
<div>
  <h5>Procedure</h5>
  <%= select_tag :service, options_for_select(Service.distinct_by_name), prompt: "", class: 'form-control' %>
</div>
<div>
  <h5>Location</h5>
  <%= select_tag :city, options_for_select(Location.distinct_cities), prompt: "", class: 'form-control' %>
</div>
<div>
  <%= submit_tag "Search Now", class: 'btn btn-success btn-block', id: 'search_button' %>
</div>
<% end %>

app/views/application/_signed_in.html.erb
<li>
  <%= link_to current_user.email, edit_user_registration_path %>
</li>
<li>
  
  <li>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  </li>

app/views/application/_signed_out.html.erb
<li>
  <%= link_to "Sign in", new_user_session_path %>
</li>
<li>
  <%= link_to "Register", new_user_registration_path %>
</li>