config/routes.rb
Medglobal::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :clinic_requests
  get "home/index"
  resources :shops do 
    resources :locations
    resources :services
    resources :staffs
    resources :promotions
    resources :reviews
    resources :appointments
    resources :messages
    resources :photos
  end

  get "/about", to: 'pages#show', id: 'about_us'
  get "/terms", to: 'pages#show', id: 'terms'
  get "/privacy", to: 'pages#show', id: 'privacy'

  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/appointment.rb
class Appointment < Message

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :services
  has_and_belongs_to_many :shops
end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  belongs_to :shop
end

app/models/clinic_request.rb
class ClinicRequest < Message
  REQUEST_DATA = [:staff_info, :location, 
                  :name, :email, 
                  :shop_info, :legal,
                  :clinic_name]

  attr_accessor *REQUEST_DATA

  QUESTIONS = 
    { 
      staff_info: "How many doctors do you have?",
      location: "What is your address?",
      name: "Contact Person's Name",
      phone: "Contact Phone Number",
      email: "Email Address",
      shop_info: "What kind of services do you provide?",
      legal: "Have you or your staff encountered any legal problems/issues?",
      clinic_name: "What is the name of your clinic/hospital?"
    }

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :shop

  # validates :name, presence: true
  validates :address, presence: true
  validates :tel, presence: true
  validates :url, presence: true

  def self.by_city(city_name)
    where("city = ?", city_name)
  end

  reverse_geocoded_by :lat, :lng do |obj,results|
    if geo = results.first
      obj.city    = geo.city
      obj.zipcode = geo.postal_code
      obj.country = geo.country
    end
  end
  after_validation :reverse_geocode, if: -> { lat.present? and lng.present? }
  
  def self.distinct_cities
    pluck(:city).compact.uniq
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
  belongs_to :shop

  attr_accessor :phone

  after_create :collect_name_and_phone, if: -> { phone and user }

  def collect_name_and_phone
    user.phone = phone
    user.save
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :shop

  mount_uploader :name, ImageUploader

  def self.main_only
    where(main: true).first
  end
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  belongs_to :location
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :shop

  validates :score, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :shop


  def self.distinct_by_name
    pluck(:name).uniq
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :reviews,      dependent: :destroy
  has_many :promotions,   dependent: :destroy
  has_many :certificates, dependent: :destroy
  has_many :staffs,        dependent: :destroy
  has_many :photos,       dependent: :destroy
  has_many :services,     dependent: :destroy
  has_many :locations,    dependent: :destroy
  has_many :users, through: :reviews

  has_many :messages
  has_many :appointments

  validates :name, presence: true
  
  accepts_nested_attributes_for :locations, reject_if: :all_blank
  accepts_nested_attributes_for :services, reject_if: :all_blank
  accepts_nested_attributes_for :staffs, reject_if: :all_blank

  has_and_belongs_to_many :categories
  belongs_to :user

  # allowing the shop to be searched by city name
  def self.by_city(city_name) 
    city_name.present? ? joins(:locations).where(locations: { city: city_name }) : all
  end

  # allowing the shop to be searched by country name
  def self.by_country(country_name)
    country_name.present? ? joins(:locations).where(locations: { country: country_name }) : all
  end

  def self.by_service(service_name)
    service_name.present? ? joins(:services).where(services: { name: service_name }) : all
  end

  def self.by_category(category_id)
    category_id.present? ? joins(:categories).where(categories: { id: category_id }) : all
  end

  def average_score
    if reviews.count > 0
      reviews.sum(:score) / reviews.count
    else 0 end
  end
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :shop

  mount_uploader :avatar, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :shops
  has_many :messages
  has_many :appointments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    read_attribute(:name) || read_attribute(:email)
  end
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper

  def render_lead_collector
    if user_signed_in?
      render 'lead'
    else
      render 'auth_request'
    end
  end
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50048707-1', 'clinicsabroad.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>ClinicsAbroad</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'navigation' %>
  <div class='container'>
    <!-- <#%= render 'navigation' %> -->
    <%= render 'flash' %>
    <%= yield %>

    <%= render 'footer' %>
  </div>
  <!-- <%#= render 'layouts/ga' if Rails.env.production? %> -->
  <script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
  analytics.load("aL35dCp8UII6qCsfFcKv7G4OayamzlOD");
  analytics.page('test');
  analytics.track('Test Event');
  }}();

</script>
</body>

</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClinicsAbroad</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <%= render 'navigation' %>
  <%= render 'flash' %>

  <%= yield %>

  <div class='container'>
    <%= render 'footer' %>
  </div>
</body>
</html>

app/views/layouts/shop_profile_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClinicsAbroad</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <%= render 'navigation' %>
    <%= render 'flash' %>
    <div class='row'>
      <div class='col-md-8'>
        <%= yield %>
      </div>
      <div class='col-md-4'>
        <ul class="nav nav-pills nav-stacked">
          <li>
            <%= link_to "Clinic Details", edit_shop_path(@shop) %>
          </li>
          <li>
            <%= link_to "Location Details", shop_locations_path(@shop) %>
          </li>
          <li>
            <%= link_to "Procedure Details", shop_services_path(@shop) %>
          </li>
          <li>
            <%= link_to "Staff Details", shop_staffs_path(@shop) %>
          </li>
          <li>
            <%= link_to "Promotion Details", shop_promotions_path(@shop) %>
          </li>
          <li>
            <%= link_to "Clinic Photo Details", shop_photos_path(@shop) %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</body>
</html>